_target_: hydra_plugins.hydra_ray_launcher.ray_aws_launcher.RayAWSLauncher
env_setup:
  pip_packages:
    omegaconf: null
    hydra_core: null
    ray: null
    cloudpickle: null
    pickle5: null
    hydra_ray_launcher: null
  commands: []
ray:
  init:
    address: auto
  remote:
    num_cpus: 2 
    num_gpus: 0.25
  cluster:
    cluster_name: gnosis-cluster
    min_workers: 0
    max_workers: 4
    initial_workers: 0
    autoscaling_mode: default
    target_utilization_fraction: 0.75
    idle_timeout_minutes: 2
    docker:
      image: 'samuelstanton/gnosis:py3.8_cuda11'
      container_name: 'gnosis-container'
      pull_before_run: true
      run_options: ["--gpus='all' --shm-size=8g"]
    provider:
      type: aws
      region: us-east-2
      availability_zone: us-east-2b
      cache_stopped_nodes: false
    auth:
      ssh_user: ubuntu
    head_node:
      IamInstanceProfile:
        Arn: arn:aws:iam::312649332277:instance-profile/ray-head-v1
      InstanceType: p2.8xlarge
      ImageId: ami-05dbf07a8f95e1073
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 200
      SubnetIds:
        - subnet-7df0af07
    worker_nodes:
      IamInstanceProfile:
        Arn: arn:aws:iam::312649332277:instance-profile/ray-worker-v1
      InstanceType: p2.8xlarge
      ImageId: ami-05dbf07a8f95e1073
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 200
      SubnetIds:
        - subnet-7df0af07
    setup_commands:
      - python -m pip install -r requirements.txt
      - python -m pip install -e .


