# @package _group_
_target_: gnosis.models.SNGAN
_recursive_: False
name: sngan
weight_dir: data/experiments/image_generation/sngan_${dataset.name}_v0.0.5
gen_cfg:
  _target_: oil.architectures.img_gen.resnetgan.Generator
  img_channels: 3
  z_dim: 128
  k: 256
disc_cfg:
  _target_: oil.architectures.img_gen.resnetgan.Discriminator
  img_channels: 3
  k: 128
  out_size: 1