_target_: gnosis.models.SNGAN
_recursive_: False
name: sngan
ckpt_dir: test/${density_model.name}_${dataset.name}_${version}
ckpt_pattern: "*generator_100000.ckpt"
gen_cfg:
  _target_: gnosis.models.sngan.Generator
  img_channels: 3
  z_dim: 128
  k: 256
disc_cfg:
  _target_: gnosis.models.sngan.Discriminator
  img_channels: 3
  k: 128
  out_size: 1