defaults:
  - dataset: cifar10
  - model: preresnet
  - logger: local

augmentation:
  random_apply:
    _target_: torchvision.transforms.RandomApply
    p: 1.
  #geometric
  rotation:
    _target_: torchvision.transforms.RandomRotation
    degrees: 90
  crop:
    _target_: torchvision.transforms.RandomCrop
    size: ${dataset.input_size}
    padding: 4
  horizontal_flip:
    _target_: torchvision.transforms.RandomHorizontalFlip
  vertical_flip:
    _target_: torchvision.transforms.RandomVerticalFlip
  perspective:
    _target_: torchvision.transforms.RandomPerspective
    distortion_scale: 0.5
    p: 0.5
  #colorspace
  grayscale:
    _target_: torchvision.transforms.RandomGrayscale
    p: 0.1
  colorjitter:
    _target_: torchvision.transforms.ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
  gaussian_blur:
    _target_: torchvision.transforms.GaussianBlur
    kernel_size: 3
    sigma:
      - 0.1
      - 2.0
  transforms_list: crop,horizontal_flip


teacher:
  num_components: 2
  use_ckpts: True
  ckpt_dir: ${data_dir}/resnet32_cifar10_ckpts

trainer:
  num_epochs: 200
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.1
    weight_decay: 1e-4
    momentum: 0.9
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: ${trainer.num_epochs}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 256
  shuffle: True

# Directories for loading and storing data
seed:
trial_id: 0
exp_name: test
data_dir: data/experiments/image_classification
log_dir: ${data_dir}/${exp_name}/trial_${trial_id}/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ./${log_dir}
  sweep:
    dir: ./${log_dir}
    subdir: .
