# @package hydra.sweeper
_target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper
max_batch_size: null
ax_config:
  max_trials: 32
  early_stop:
    minimize: true
    max_epochs_without_improvement: 16
    epsilon: 1.0e-05
  experiment:
    name: distillation_tuning
    objective_name: test_error
    minimize: true
    parameter_constraints: null
    outcome_constraints: null
    status_quo: null
  client:
    verbose_logging: false
    random_seed: null
  params:
    trainer.optimizer.lr:
      type: range
      bounds: [1e-4, 1e-1]
      log_scale: True
    trainer.optimizer.momentum:
      type: range
      bounds: [1e-6, 0.99]
      log_scale: True
    trainer.optimizer.nesterov:
      type: choice
      values: [True, False]
    trainer.synth_aug.ratio:
      type: range
      bounds: [1e-6, 0.5]
      log_scale: True
    dataloader.batch_size:
      type: choice
      values: [32, 64]
