defaults:
  - dataset: cifar100
  - density_model: sngan
  - logger: local

trainer:
  num_gen_updates: 100000  # total number of generator gradient updates
  gen_update_period: 5  # number of minibatches per generator update
  disc_update_period: 1  # number of minibatches per discriminator update
  eval_period: 1000  # number of generator updates per evaluation
  eval_dataset: test
  num_eval_samples: 5000  # number of generator samples for FID and IS
  checkpoint_period: 10000  # number of generator updates per checkpoint
  optimizer:
    lr: 2e-4
    beta1: 0.0
    beta2: 0.9
  lr_decay:
    min_lr: 1e-6
    start: 0
    stop: ${trainer.num_gen_updates}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  shuffle: True
  num_workers: 1

augmentation:
  transforms_list:
    - horizontal_flip
  normalization: unitcube
  crop:
    _target_: torchvision.transforms.RandomCrop
    size: ${dataset.input_size}
    padding: 4
  horizontal_flip:
    _target_: torchvision.transforms.RandomHorizontalFlip
  resize:
    _target_: torchvision.transforms.Resize
    size: 64


# Directories for loading and storing data
seed:
trial_id: 0

dataset_dir: data/datasets
data_dir: data/experiments/image_generation
exp_name: test/${density_model.name}_${dataset.name}_${version}
job_name: null
timestamp: ${now:%Y-%m-%d_%H-%M-%S}
log_dir: ${data_dir}/${exp_name}

project_name: gnosis
version: v0.1.0

hydra:
  run:
    dir: ./${log_dir}
  sweep:
    dir: ./${log_dir}
    subdir: .