defaults:
  - dataset: cifar10
  - density_model: sngan
  - logger: local
  - hydra/launcher: basic

trainer:
  num_epochs: 500
  num_disc_updates: 5
  optimizer:
    lr: 2e-4
    beta1: 0.5
    beta2: 0.999

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: True
  num_workers: 2

augmentation:
  transforms_list: horizontal_flip
  normalization: max_min
  crop:
    _target_: torchvision.transforms.RandomCrop
    size: ${dataset.input_size}
    padding: 4
  horizontal_flip:
    _target_: torchvision.transforms.RandomHorizontalFlip
  resize:
    _target_: torchvision.transforms.Resize
    size: 64


# Directories for loading and storing data
checkpoint_freq: 100
seed:
trial_id: 0
exp_name: ${density_model.name}_${dataset.name}_${version}
data_dir: data/experiments/image_generation
log_dir: ${data_dir}/${exp_name}/trial_${trial_id}/${now:%Y-%m-%d_%H-%M-%S}
project_name: gnosis
version: v0.0.4

hydra:
  run:
    dir: ./${log_dir}
  sweep:
    dir: ./${log_dir}
    subdir: .