init:
  _target_: torchvision.datasets.CIFAR100
  root: ${dataset_dir}/cifar100
  download: True

name: cifar100
num_classes: 100
input_size: 32
shuffle_train_targets:
  enabled: False
  seed: 0
  ratio: 1.0
subsample:
  ratio: 1.0
  seed: 0
  split: 0
# https://gist.github.com/weiaicunzai/e623931921efefd4c331622c344d8151
statistics:
  mean_statistics:
    - 0.5071
    - 0.4867
    - 0.4408
  std_statistics:
    - 0.2675
    - 0.2565
    - 0.2761
  max:
    - 1.0
    - 1.0
    - 1.0
  min:
    - 0.0
    - 0.0
    - 0.0